'use client';

import { useState, useEffect } from 'react';
import * as React from 'react';
import { toast } from 'sonner';
import { Loader2, CalendarIcon } from 'lucide-react';
import Image from 'next/image';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { useQueries } from '@tanstack/react-query';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import type { CampaignFormData } from '@/hooks/use-campaign-management';
import {
  CAMPAIGN_STATUS_OPTIONS,
  CAMPAIGN_TYPE_OPTIONS,
  MMP_OPTIONS,
  REGION_OPTIONS,
} from '@/hooks/use-campaign-management';
import type { Game } from '@/hooks/use-game-management';
import { PLATFORM_OPTIONS } from '@/hooks/use-game-management';

interface CreateCampaignFormProps {
  isOpen: boolean;
  onClose: () => void;
  onCreateCampaign: (campaignData: CampaignFormData) => Promise<any>;
  accountId: string;
  games: Game[];
}

export function CreateCampaignForm({
  isOpen,
  onClose,
  onCreateCampaign,
  accountId,
  games,
}: CreateCampaignFormProps) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [newCampaign, setNewCampaign] = useState<CampaignFormData>({
    account_id: accountId,
    game_id: null,
    name: '',
    description: null,
    region: '',
    mmp: '',
    campaign_type: '',
    start_date: '',
    end_date: null,
    status: '',
    jira_url: null,
    daily_report_url: null,
  });

  // TanStack Query로 모든 게임 이미지 가져오기
  const gameImageQueries = useQueries({
    queries: games.map((game) => ({
      queryKey: ['game-info', game.store_url],
      queryFn: async () => {
        if (!game.store_url) return { logo_url: null };
        const response = await fetch('/api/fetch-game-info', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ url: game.store_url }),
        });
        if (!response.ok) return { logo_url: null };
        const result = await response.json();
        return result.data || { logo_url: null };
      },
      enabled: !!game.store_url,
      staleTime: 1000 * 60 * 5,
      gcTime: 1000 * 60 * 10,
      retry: 1,
    })),
  });

  // 게임 이미지 맵 생성
  const gameImages = React.useMemo(() => {
    const imageMap: Record<string, string | null> = {};
    games.forEach((game, index) => {
      const query = gameImageQueries[index];
      if (query?.data?.logo_url) {
        imageMap[game.id] = query.data.logo_url;
      } else {
        imageMap[game.id] = null;
      }
    });
    return imageMap;
  }, [games, gameImageQueries]);

  // 선택된 게임 이미지
  const selectedGameImage = React.useMemo(() => {
    if (newCampaign.game_id && gameImages[newCampaign.game_id]) {
      return gameImages[newCampaign.game_id];
    }
    return null;
  }, [newCampaign.game_id, gameImages]);

  // Dialog가 열릴 때 폼 초기화
  useEffect(() => {
    if (isOpen) {
      setNewCampaign({
        account_id: accountId,
        game_id: null,
        name: '',
        description: null,
        region: '',
        mmp: '',
        campaign_type: '',
        start_date: '',
        end_date: null,
        status: '',
        jira_url: null,
        daily_report_url: null,
      });
    }
  }, [isOpen, accountId]);

  // Game과 Region이 선택되면 Campaign Name 자동 생성
  useEffect(() => {
    // Campaign Name이 비어있고 Game과 Region이 모두 선택되었을 때만 자동 생성
    if (!newCampaign.name.trim() && newCampaign.game_id && newCampaign.region) {
      const selectedGame = games.find((g) => g.id === newCampaign.game_id);
      if (selectedGame) {
        const autoGeneratedName = `${selectedGame.game_name}_${newCampaign.region}`;
        setNewCampaign((prev) => ({
          ...prev,
          name: autoGeneratedName,
        }));
      }
    }
  }, [newCampaign.game_id, newCampaign.region, newCampaign.name, games]);

  const validateForm = (): boolean => {
    if (games.length === 0) {
      toast.error('Please add a game first before creating a campaign.');
      return false;
    }

    if (!newCampaign.name.trim()) {
      toast.error('Please enter campaign name.');
      return false;
    }

    if (!newCampaign.game_id) {
      toast.error('Please select a game.');
      return false;
    }

    if (!newCampaign.start_date) {
      toast.error('Please select start date.');
      return false;
    }

    if (!newCampaign.region) {
      toast.error('Please select region.');
      return false;
    }

    if (!newCampaign.mmp) {
      toast.error('Please select MMP.');
      return false;
    }

    if (!newCampaign.campaign_type) {
      toast.error('Please select campaign type.');
      return false;
    }

    if (
      newCampaign.end_date &&
      new Date(newCampaign.start_date) > new Date(newCampaign.end_date)
    ) {
      toast.error('End date must be after start date.');
      return false;
    }

    return true;
  };

  const handleCreateCampaign = async () => {
    if (!validateForm()) return;

    try {
      setIsSubmitting(true);

      const campaignData: CampaignFormData = {
        account_id: newCampaign.account_id,
        game_id: newCampaign.game_id,
        name: newCampaign.name.trim(),
        description: newCampaign.description?.trim() || null,
        region: newCampaign.region,
        mmp: newCampaign.mmp,
        campaign_type: newCampaign.campaign_type,
        start_date: newCampaign.start_date,
        end_date: newCampaign.end_date,
        status: newCampaign.status,
        jira_url: newCampaign.jira_url?.trim() || null,
        daily_report_url: newCampaign.daily_report_url?.trim() || null,
      };

      await onCreateCampaign(campaignData);
      toast.success('Campaign created successfully.');
      onClose();
    } catch (error) {
      const errorMessage =
        error instanceof Error
          ? error.message
          : 'An error occurred while creating the campaign.';
      toast.error(`Campaign creation error: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className='max-w-2xl max-h-[90vh] overflow-y-auto'>
        <DialogHeader>
          <DialogTitle>Create New Campaign</DialogTitle>
          <DialogDescription>
            Create a new campaign. Please fill in all required fields.
          </DialogDescription>
        </DialogHeader>

        <div className='space-y-4 py-4'>
          {/* Campaign Name */}
          <div className='space-y-2'>
            <Label htmlFor='campaign-name'>
              Campaign Name <span className='text-red-500'>*</span>
            </Label>
            <Input
              id='campaign-name'
              placeholder='Enter campaign name'
              value={newCampaign.name}
              onChange={(e) =>
                setNewCampaign({ ...newCampaign, name: e.target.value })
              }
              autoComplete='off'
            />
          </div>

          {/* Game Selection */}
          <div className='space-y-2'>
            <Label htmlFor='game'>
              Game <span className='text-red-500'>*</span>
            </Label>
            <Select
              value={newCampaign.game_id || ''}
              onValueChange={(value) =>
                setNewCampaign({
                  ...newCampaign,
                  game_id: value,
                })
              }
            >
              <SelectTrigger id='game' className='w-full'>
                <div className='flex items-center gap-2 flex-1 w-full'>
                  {selectedGameImage && (
                    <Image
                      src={selectedGameImage}
                      alt={
                        games.find((g) => g.id === newCampaign.game_id)
                          ?.game_name || 'Game'
                      }
                      width={20}
                      height={20}
                      className='rounded-lg object-contain'
                      unoptimized
                    />
                  )}
                  {newCampaign.game_id ? (
                    (() => {
                      const selectedGame = games.find(
                        (g) => g.id === newCampaign.game_id
                      );
                      const platformLabel =
                        PLATFORM_OPTIONS.find(
                          (opt) => opt.value === selectedGame?.platform
                        )?.label ||
                        selectedGame?.platform ||
                        '';
                      return (
                        <>
                          <span className='flex-1 text-left truncate'>
                            {selectedGame?.game_name || 'Select a game'}
                          </span>
                          {platformLabel && (
                            <span className='text-xs text-muted-foreground flex-shrink-0'>
                              {platformLabel}
                            </span>
                          )}
                        </>
                      );
                    })()
                  ) : (
                    <span className='flex-1 text-left'>Select a game</span>
                  )}
                </div>
              </SelectTrigger>
              <SelectContent>
                {games.map((game) => (
                  <SelectItem key={game.id} value={game.id} className='w-full'>
                    <div className='flex items-center gap-2 w-full pr-0'>
                      {gameImages[game.id] ? (
                        <Image
                          src={gameImages[game.id]!}
                          alt={game.game_name}
                          width={20}
                          height={20}
                          className='rounded-lg object-contain flex-shrink-0'
                          unoptimized
                        />
                      ) : (
                        <div className='w-5 h-5 rounded-lg bg-muted flex items-center justify-center flex-shrink-0'>
                          <span className='text-xs text-muted-foreground'>
                            ?
                          </span>
                        </div>
                      )}
                      <span className='truncate flex-1'>{game.game_name}</span>
                      {(() => {
                        const platformLabel =
                          PLATFORM_OPTIONS.find(
                            (opt) => opt.value === game.platform
                          )?.label ||
                          game.platform ||
                          '';
                        return (
                          <span className='text-xs text-muted-foreground flex-shrink-0 ml-auto'>
                            {platformLabel}
                          </span>
                        );
                      })()}
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Region and MMP */}
          <div className='grid grid-cols-2 gap-4'>
            <div className='space-y-2'>
              <Label htmlFor='region'>
                Region <span className='text-red-500'>*</span>
              </Label>
              <Select
                value={newCampaign.region || undefined}
                onValueChange={(value) =>
                  setNewCampaign({ ...newCampaign, region: value })
                }
              >
                <SelectTrigger id='region'>
                  <SelectValue placeholder='Select Region'>
                    {(() => {
                      if (!newCampaign.region) return '';
                      const regionOption = REGION_OPTIONS.find(
                        (opt) => opt.value === newCampaign.region
                      );
                      const regionEmojiMap: Record<string, string> = {
                        KR: '🇰🇷',
                        JP: '🇯🇵',
                        TW: '🇹🇼',
                        US: '🇺🇸',
                      };
                      const emoji = regionEmojiMap[newCampaign.region] || '';
                      return regionOption
                        ? `${emoji} ${regionOption.label}`
                        : '';
                    })()}
                  </SelectValue>
                </SelectTrigger>
                <SelectContent>
                  {REGION_OPTIONS.map((option) => {
                    const regionEmojiMap: Record<string, string> = {
                      KR: '🇰🇷',
                      JP: '🇯🇵',
                      TW: '🇹🇼',
                      US: '🇺🇸',
                    };
                    const emoji = regionEmojiMap[option.value] || '';
                    return (
                      <SelectItem key={option.value} value={option.value}>
                        {emoji} {option.label}
                      </SelectItem>
                    );
                  })}
                </SelectContent>
              </Select>
            </div>

            <div className='space-y-2'>
              <Label htmlFor='mmp'>
                MMP <span className='text-red-500'>*</span>
              </Label>
              <Select
                value={newCampaign.mmp || undefined}
                onValueChange={(value) =>
                  setNewCampaign({ ...newCampaign, mmp: value })
                }
              >
                <SelectTrigger id='mmp' className='w-full'>
                  {newCampaign.mmp ? (
                    <div className='flex items-center gap-2 flex-1'>
                      {newCampaign.mmp === 'Adjust' && (
                        <div className='flex items-center justify-center w-5 h-5'>
                          <Image
                            src='/Adjust Logo.svg'
                            alt='Adjust'
                            width={20}
                            height={20}
                            className='object-contain'
                            unoptimized
                          />
                        </div>
                      )}
                      {newCampaign.mmp === 'AppsFlyer' && (
                        <div className='flex items-center justify-center w-5 h-5'>
                          <Image
                            src='/AppsFlyer Logo.svg'
                            alt='AppsFlyer'
                            width={20}
                            height={20}
                            className='object-contain'
                            style={{ width: 'auto', height: 'auto' }}
                            unoptimized
                          />
                        </div>
                      )}
                      <span className='flex-1 text-left'>
                        {MMP_OPTIONS.find(
                          (opt) => opt.value === newCampaign.mmp
                        )?.label || 'Select MMP'}
                      </span>
                    </div>
                  ) : (
                    <SelectValue placeholder='Select MMP' />
                  )}
                </SelectTrigger>
                <SelectContent>
                  {MMP_OPTIONS.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      <div className='flex items-center gap-2'>
                        {option.value === 'Adjust' && (
                          <div className='flex items-center justify-center w-5 h-5'>
                            <Image
                              src='/Adjust Logo.svg'
                              alt='Adjust'
                              width={20}
                              height={20}
                              className='object-contain'
                              unoptimized
                            />
                          </div>
                        )}
                        {option.value === 'AppsFlyer' && (
                          <div className='flex items-center justify-center w-5 h-5'>
                            <Image
                              src='/AppsFlyer Logo.svg'
                              alt='AppsFlyer'
                              width={20}
                              height={20}
                              className='object-contain'
                              style={{ width: 'auto', height: 'auto' }}
                              unoptimized
                            />
                          </div>
                        )}
                        <span>{option.label}</span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Campaign Type and Status */}
          <div className='grid grid-cols-2 gap-4'>
            <div className='space-y-2'>
              <Label htmlFor='campaign-type'>
                Campaign Type <span className='text-red-500'>*</span>
              </Label>
              <Select
                value={newCampaign.campaign_type || undefined}
                onValueChange={(value) =>
                  setNewCampaign({ ...newCampaign, campaign_type: value })
                }
              >
                <SelectTrigger id='campaign-type'>
                  <SelectValue placeholder='Select Campaign Type' />
                </SelectTrigger>
                <SelectContent>
                  {CAMPAIGN_TYPE_OPTIONS.map((option) => (
                    <SelectItem key={option.value} value={option.value}>
                      {option.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className='space-y-2'>
              <Label htmlFor='status'>
                Status <span className='text-red-500'>*</span>
              </Label>
              <Select
                value={newCampaign.status || undefined}
                onValueChange={(value) =>
                  setNewCampaign({ ...newCampaign, status: value })
                }
              >
                <SelectTrigger id='status'>
                  {newCampaign.status ? (
                    <span
                      className={
                        newCampaign.status === 'planning'
                          ? 'text-yellow-600 dark:text-yellow-500'
                          : newCampaign.status === 'ongoing'
                          ? 'text-green-600 dark:text-green-500'
                          : newCampaign.status === 'holding'
                          ? 'text-red-600 dark:text-red-500'
                          : newCampaign.status === 'end'
                          ? 'text-gray-500 dark:text-gray-400'
                          : ''
                      }
                    >
                      {CAMPAIGN_STATUS_OPTIONS.find(
                        (opt) => opt.value === newCampaign.status
                      )?.label || 'Select status'}
                    </span>
                  ) : (
                    <SelectValue placeholder='Select Status' />
                  )}
                </SelectTrigger>
                <SelectContent>
                  {CAMPAIGN_STATUS_OPTIONS.map((option) => {
                    const getStatusColor = (status: string) => {
                      switch (status) {
                        case 'planning':
                          return 'text-yellow-600 dark:text-yellow-500';
                        case 'ongoing':
                          return 'text-green-600 dark:text-green-500';
                        case 'holding':
                          return 'text-red-600 dark:text-red-500';
                        case 'end':
                          return 'text-gray-500 dark:text-gray-400';
                        default:
                          return '';
                      }
                    };
                    return (
                      <SelectItem key={option.value} value={option.value}>
                        <span className={getStatusColor(option.value)}>
                          {option.label}
                        </span>
                      </SelectItem>
                    );
                  })}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Start Date and End Date */}
          <div className='grid grid-cols-2 gap-4'>
            <div className='space-y-2'>
              <Label htmlFor='start-date'>
                Start Date <span className='text-red-500'>*</span>
              </Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    id='start-date'
                    variant='outline'
                    className='w-full justify-start text-left font-normal'
                  >
                    <span className='flex-1 text-left'>
                      {newCampaign.start_date
                        ? (() => {
                            const date = new Date(newCampaign.start_date);
                            const year = date.getFullYear();
                            const month = String(date.getMonth() + 1).padStart(
                              2,
                              '0'
                            );
                            const day = String(date.getDate()).padStart(2, '0');
                            return `${year}/${month}/${day}`;
                          })()
                        : 'Select start date'}
                    </span>
                    <CalendarIcon className='ml-auto h-4 w-4 opacity-50' />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className='w-auto p-0' align='start'>
                  <Calendar
                    mode='single'
                    captionLayout='dropdown'
                    selected={
                      newCampaign.start_date
                        ? new Date(newCampaign.start_date)
                        : undefined
                    }
                    onSelect={(date) => {
                      if (date) {
                        const year = date.getFullYear();
                        const month = String(date.getMonth() + 1).padStart(
                          2,
                          '0'
                        );
                        const day = String(date.getDate()).padStart(2, '0');
                        setNewCampaign({
                          ...newCampaign,
                          start_date: `${year}-${month}-${day}`,
                        });
                      }
                    }}
                    fromYear={1900}
                    toYear={2100}
                    formatters={{
                      formatMonthDropdown: (date) =>
                        date.toLocaleString('en-US', { month: 'short' }),
                    }}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>

            <div className='space-y-2'>
              <Label htmlFor='end-date'>End Date</Label>
              <Popover>
                <PopoverTrigger asChild>
                  <Button
                    id='end-date'
                    variant='outline'
                    className='w-full justify-start text-left font-normal'
                  >
                    <span className='flex-1 text-left'>
                      {newCampaign.end_date
                        ? (() => {
                            const date = new Date(newCampaign.end_date);
                            const year = date.getFullYear();
                            const month = String(date.getMonth() + 1).padStart(
                              2,
                              '0'
                            );
                            const day = String(date.getDate()).padStart(2, '0');
                            return `${year}/${month}/${day}`;
                          })()
                        : 'Select end date'}
                    </span>
                    <CalendarIcon className='ml-auto h-4 w-4 opacity-50' />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className='w-auto p-0' align='start'>
                  <Calendar
                    mode='single'
                    captionLayout='dropdown'
                    selected={
                      newCampaign.end_date
                        ? new Date(newCampaign.end_date)
                        : undefined
                    }
                    onSelect={(date) => {
                      if (date) {
                        const year = date.getFullYear();
                        const month = String(date.getMonth() + 1).padStart(
                          2,
                          '0'
                        );
                        const day = String(date.getDate()).padStart(2, '0');
                        setNewCampaign({
                          ...newCampaign,
                          end_date: `${year}-${month}-${day}`,
                        });
                      }
                    }}
                    fromYear={1900}
                    toYear={2100}
                    formatters={{
                      formatMonthDropdown: (date) =>
                        date.toLocaleString('en-US', { month: 'short' }),
                    }}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>
          </div>

          {/* Jira URL */}
          <div className='space-y-2'>
            <Label htmlFor='jira-url'>Jira URL</Label>
            <Input
              id='jira-url'
              placeholder='https://jira.example.com/issue/XXX'
              value={newCampaign.jira_url || ''}
              onChange={(e) =>
                setNewCampaign({
                  ...newCampaign,
                  jira_url: e.target.value || null,
                })
              }
              autoComplete='off'
            />
          </div>

          {/* Daily Report URL */}
          <div className='space-y-2'>
            <Label htmlFor='daily-report-url'>Daily Report URL</Label>
            <Input
              id='daily-report-url'
              placeholder='https://example.com/daily-report'
              value={newCampaign.daily_report_url || ''}
              onChange={(e) =>
                setNewCampaign({
                  ...newCampaign,
                  daily_report_url: e.target.value || null,
                })
              }
              autoComplete='off'
            />
          </div>

          {/* Description */}
          <div className='space-y-2'>
            <Label htmlFor='description'>Description</Label>
            <Input
              id='description'
              placeholder='Enter campaign description (optional)'
              value={newCampaign.description || ''}
              onChange={(e) =>
                setNewCampaign({
                  ...newCampaign,
                  description: e.target.value || null,
                })
              }
              autoComplete='off'
            />
          </div>
        </div>

        <DialogFooter>
          <Button
            type='button'
            variant='outline'
            onClick={onClose}
            disabled={isSubmitting}
          >
            Cancel
          </Button>
          <Button
            type='button'
            onClick={handleCreateCampaign}
            disabled={isSubmitting}
          >
            {isSubmitting && <Loader2 className='mr-2 h-4 w-4 animate-spin' />}
            Create Campaign
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
